# Generated by Django 3.1.2 on 2022-09-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20220918_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
