# Generated by Django 3.1.2 on 2022-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_auto_20220918_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.FilePathField(default=0, path='phones/images/'),
            preserve_default=False,
        ),
    ]
